---
driver:
  name: dokken
  chef_version: 12
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[ds_nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
